### PR TITLE
Fix alerts on LGTM.com

### PR DESCRIPTION
**Pull request by fredden**
There are currently three code-quality issues identified on https://lgtm.com/projects/g/genecommerce/module-braintree-magento2/alerts/. This pull request solves these, with no impact to functionality.

### CODE REVIEW

**Comment by fredden** [comment]
@kartikmaniyar why was this closed?

**Comment by kartikmaniyar** [comment]
As it has already fixed via this PR: https://github.com/genecommerce/module-braintree-magento2/pull/158

**Comment by fredden** [comment]
Thanks for confirming. It looks like this is another case where you've fixed something in duplicate / that already had an open pull request.

**Comment by kartikmaniyar** [comment]
@fredden Sorry but I wasn't sure about this open PR that's why I have submitted the PR against the issue.

**Pull request closed without merging**
