### PR TITLE
guest quote id for apple pay - No such entity with cartId = [] []

### PR DESCRIPTION
**Pull request by cdiacon**
error - main.CRITICAL: No such entity with cartId = [] []

Replicate :
* enable production mode
* enable apple pay payment
* go on frontend and navigate around as a guest
* see error in system.log file

### CODE REVIEW

**Comment by EmilyPepperman** [comment]
We have this issue Gene Commerce... please merge Calin's pull request! @AidanThreadgold  :-)

**Comment by paul-gene** [comment]
@cdiacon simply removing the Quote ID does not seem like a great idea. What happens after you add a product to your cart and navigate the site?

**Comment by EmilyPepperman** [comment]
@paul-gene We have had this fix on our production site for a couple of weeks now and works fine. No more errors in system.log of error - main.CRITICAL: No such entity with cartId = [] []

**Comment by paul-gene** [comment]
@EmilyPepperman can you confirm that there is no detrimental effect with removing this?

**Comment by cdiacon** [comment]
@paul-gene 

I was about to dig into and look for a different solution to this but then I have found this change that is properly catching the exception and looks for the error message that is excluding 
"No such entity with cartId ="

https://github.com/genecommerce/module-braintree-magento2/commit/9d485389edea150023cb15abcf6051240451803d#diff-a59574c84d58c5887beaf70002cadfb0R78

Paul, I am closing this PR as this is fixed and released on 3.1.2 version. Thanks.

**Pull request closed without merging**
